### ISSUE TITLE
Support for WooCommerce 5.4.1

### ISSUE THREAD

**Issue by mikef-nl** [Netcash-ZA/PayNow-WooCommerce#2]
The current plugin crashes WooCommerce on the following lines:
`require_once( plugin_basename( 'vendor/netcash/paynow-php/AutoLoader.php' ) );
	// Autoload the SDK.
	\Netcash\PayNow\AutoLoader::register();`

**Comment by mikef-nl** [comment]
Warning: require_once(vendor/netcash/paynow-php/AutoLoader.php): failed to open stream: No such file or directory in /home/dapfnrnp/public_html/staging/wp-content/plugins/paynow-woocommerce/gateway-paynow.php on line 57

Fatal error: require_once(): Failed opening required 'vendor/netcash/paynow-php/AutoLoader.php' (include_path='.:/opt/alt/php74/usr/share/pear') in /home/dapfnrnp/public_html/staging/wp-content/plugins/paynow-woocommerce/gateway-paynow.php on line 57

**Comment by mikef-nl** [comment]
Seems like the link on the on the Netcash site is wrong ? https://github.com/Netcash-ZA/PayNow-WooCommerce/archive/master.zip. Gives source code and not the gateway-paynow.zip

**Comment by iedev1** [comment]
Apologies for that. Please use the latest _gateway-paynow.zip_ release from the [Releases page](https://github.com/Netcash-ZA/PayNow-WooCommerce/releases).

The master.zip doesn't contain all dependencies.
