### ISSUE TITLE
Wordpress crash after plugin activation

### ISSUE THREAD

**Issue by cmengelbrecht** [Netcash-ZA/PayNow-WooCommerce#3]
Wordpress: 5.8
WooCommerce 5.5.2
PHP 7.4
Netcash 4.0.4

Upload and install works fine
After activation of plugin Wordpress crash to white screen - Wordpress Admin also not accessible. Plugin needs to be renamed with FTP to get Wordpress to work again.

**Comment by iedev1** [comment]
Good day

Perhaps you downloaded the zip from the code tab?

The plugin (gateway-paynow.zip) needs to be downloaded from the [releases page](https://github.com/Netcash-ZA/PayNow-WooCommerce/releases).

If you still receive the error, please send the relevant snippet of the server's PHP error log.

**Comment by cmengelbrecht** [comment]
Thank you. Problem solved. Download the paynow gateway and all works fine
now.

Regards

Marius
